frases = [
    'No mundo ideal que eu criei, não há lugar para vocês!Kira Yamato.',
    'A vingança nunca é plena, mata a alma e a envenena - Sr. Madruga (Chaves).',
    'Já avisei, não mexam comigo. Sou perigoso quando estou zangado - Yusuke Urameshi ',
    'Eu sou o que protege os fracos dos cruéis, sou a justiça, eu sou o Batman!',
    'Corrente de Andrômeda! Shun de Andrômeda (Cavaleiros do Zodíaco)',
    'Eu sou o Goku, o defensor da Terra',
    'Terra, fogo, vento, água, coração! Com seus poderes combinados, eu sou o Capitão Planeta',
    'Meteoro de Pégasus - Seya',
    'Não importa o quão forte você seja, sempre haverá alguém mais forte para te vencer! - Rock Lee (Naruto)',
    'Não importa o quão forte você seja, sempre haverá alguém mais forte para te vencer! - Rock Lee (Naruto)',
    'Como você ousa tocar nas minhas preciosas armas? Isso é uma ofensa a todas as mulheres! - Sanji (One Piece)',
    'Pare de me cutucar, seu pedaço de gosma! - Inuyasha (Inuyasha)',
    'Vai que é tua, Taffarel! - Goku (Dragon Ball Z)',
    'Eu sou o rei dos piratas! - Monkey D. Luffy (One Piece)',
    'Uma coisa eu tenho que admitir, essa não é a pior situação que eu já estive. Só está no Top 10. - Vegeta (Dragon Ball Z)',
    'De grão em grão, a galinha enche o papo',
    'Aqui não é a casa da mãe Joana!',
    'Você precisa fazer aquilo que pensa que não é capaz de fazer.',
    'Ôxi, só love, só love!',
    'Sabe de nada, inocente!',
    'Aqui é Brasil, meu filho!',
    'Quem não arrisca, não petisca',
    'Vamo que vamo, meu povo!',
    'É hora do duelo! - Yugi Muto, Yu-Gi-Oh!',
    'Sou só um garoto, perdido no tempo e no espaço. - Edward Elric, Fullmetal Alchemist',
    'Eu sou a espada que corta o mal! - Kenshin Himura, Rurouni Kenshin',
    'Eu vou ser Hokage! Naruto',
    'Eu vou dominar os quatro elementos. Aang, O último domador de ar',
    'Você não pode tomar a pílula vermelha e voltar. Matrix',
    ' Há cem anos, viviam em harmonia os povos da Água, da Terra e do Fogo. Mas tudo mudou quando a Nação do Fogo atacou. Só o Avatar, mestre dos quatro elementos, podia impedi-los, mas quando o mundo mais precisou dele, ele desapareceu',
    'Calma aí Van Damme'
]

exports.frases = frases;